// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXlJD7N87PXllPfIRzoM961oEVFsFgrTA',
    appId: '1:929606688665:web:96e569a690c2e444263d08',
    messagingSenderId: '929606688665',
    projectId: 'cab-ren-183b2',
    authDomain: 'cab-ren-183b2.firebaseapp.com',
    storageBucket: 'cab-ren-183b2.appspot.com',
    measurementId: 'G-TQT0ZSE9KS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtle70nRhuvguVnXvg0bGQMy6Fi3ai1PM',
    appId: '1:929606688665:android:f1481a911388af2f263d08',
    messagingSenderId: '929606688665',
    projectId: 'cab-ren-183b2',
    storageBucket: 'cab-ren-183b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIwWL5wjfCmSbAhfR7A8nVPioZg35cxX4',
    appId: '1:929606688665:ios:88ebbae7da2b259f263d08',
    messagingSenderId: '929606688665',
    projectId: 'cab-ren-183b2',
    storageBucket: 'cab-ren-183b2.appspot.com',
    iosClientId: '929606688665-s8htvra1vslm8796gkqveg1g2lg96qf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cabRen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIwWL5wjfCmSbAhfR7A8nVPioZg35cxX4',
    appId: '1:929606688665:ios:88ebbae7da2b259f263d08',
    messagingSenderId: '929606688665',
    projectId: 'cab-ren-183b2',
    storageBucket: 'cab-ren-183b2.appspot.com',
    iosClientId: '929606688665-s8htvra1vslm8796gkqveg1g2lg96qf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cabRen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXlJD7N87PXllPfIRzoM961oEVFsFgrTA',
    appId: '1:929606688665:web:56433151c01fffb7263d08',
    messagingSenderId: '929606688665',
    projectId: 'cab-ren-183b2',
    authDomain: 'cab-ren-183b2.firebaseapp.com',
    storageBucket: 'cab-ren-183b2.appspot.com',
    measurementId: 'G-8CDCF04R4N',
  );

}